import { access, copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const PLUGIN_NAME = 'R3DCharacterOverlayDemo';

const pluginSource = resolve('dist/R3DCharacterOverlayDemo.js');
const sourceMapSource = resolve('dist/R3DCharacterOverlayDemo.js.map');
const modelSource = resolve('public/models/r3d-demo-character.glb');

const pluginEntry = {
  name: PLUGIN_NAME,
  status: true,
  description: 'R3D Visual Stage character overlay demo for RPG Maker MV.',
  parameters: {
    'Default Character Path': 'models/r3d-demo-character.glb',
    'Auto Show': 'true',
    'Overlay Width': '280',
    'Target FPS': '30',
    'Max Pixel Ratio': '1.5',
  },
};

const mvProjectPath = await resolveMvProjectPath();
await assertMvProject(mvProjectPath);
await copyDemoFiles(mvProjectPath);
await enablePlugin(mvProjectPath);

console.log(`Enabled ${PLUGIN_NAME} in ${mvProjectPath}`);

async function resolveMvProjectPath() {
  const localConfig = await readOptionalJson(resolve('.r3d-local.json'));
  if (typeof localConfig?.mvProjectPath === 'string' && localConfig.mvProjectPath.trim()) {
    return resolve(localConfig.mvProjectPath);
  }

  throw new Error(
    'Missing mvProjectPath. Create .r3d-local.json with { "mvProjectPath": "D:/path/to/project" }.',
  );
}

async function assertMvProject(mvProjectPath) {
  if (!(await pathExists(resolve(mvProjectPath, 'Game.rpgproject')))) {
    throw new Error(`MV project path does not contain Game.rpgproject: ${mvProjectPath}`);
  }
}

async function copyDemoFiles(mvProjectPath) {
  const pluginTargetDir = resolve(mvProjectPath, 'js/plugins');
  const modelTargetDir = resolve(mvProjectPath, 'models');

  await mkdir(pluginTargetDir, { recursive: true });
  await mkdir(modelTargetDir, { recursive: true });
  await copyFile(pluginSource, resolve(pluginTargetDir, `${PLUGIN_NAME}.js`));
  await copyOptional(sourceMapSource, resolve(pluginTargetDir, `${PLUGIN_NAME}.js.map`));
  await copyFile(modelSource, resolve(modelTargetDir, 'r3d-demo-character.glb'));
}

async function enablePlugin(mvProjectPath) {
  const pluginsPath = resolve(mvProjectPath, 'js/plugins.js');
  const source = await readFile(pluginsPath, 'utf8');
  const plugins = parseMvPlugins(source);
  const existingIndex = plugins.findIndex((plugin) => plugin?.name === PLUGIN_NAME);

  if (existingIndex >= 0) {
    plugins[existingIndex] = {
      ...plugins[existingIndex],
      ...pluginEntry,
      parameters: {
        ...pluginEntry.parameters,
        ...plugins[existingIndex].parameters,
      },
      status: true,
    };
  } else {
    plugins.push(pluginEntry);
  }

  await writeFile(pluginsPath, formatMvPlugins(plugins), 'utf8');
}

function parseMvPlugins(source) {
  const start = source.indexOf('[');
  const end = source.lastIndexOf(']');
  if (start < 0 || end < start) {
    throw new Error('Could not find the MV $plugins array in js/plugins.js.');
  }

  return JSON.parse(source.slice(start, end + 1));
}

function formatMvPlugins(plugins) {
  const body = plugins.map((plugin) => JSON.stringify(plugin)).join(',\n');
  return `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${body}\n];\n`;
}

async function readOptionalJson(path) {
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch (error) {
    if (error?.code === 'ENOENT') {
      return undefined;
    }

    throw error;
  }
}

async function copyOptional(source, target) {
  try {
    await copyFile(source, target);
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      throw error;
    }
  }
}

async function pathExists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
